version: 2.1
jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    steps:
      - checkout
      - run:
          name: bundle install
          command: gem install bundler:2.3.3
      - run:
          name: hello
          command: bundle exec rspec hello_spec.rb
workflows:
  test_workflow:
    jobs:
      - test